# Copyright (c) 2026 Ak-Suu Portal Project Team. All rights reserved.
# Proprietary software. See LICENSE for terms.
services:
  - type: web
    name: aksuu-portal
    runtime: python
    buildCommand: bash build.sh
    startCommand: bash start.sh
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 1
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: DEBUG
        value: "0"
      - key: DATABASE_URL
        sync: false
      - key: DB_CONN_MAX_AGE
        value: "0"
      - key: DATABASE_IMAGE_STORAGE
        value: "1"
      - key: ENABLE_MAINTENANCE_ENDPOINT
        value: "1"
      - key: DEPLOY_TOKEN
        sync: false
