# Copyright (c) 2026 Ak-Suu Portal Project Team. All rights reserved.
# Proprietary software. See LICENSE for terms.
"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from .environment import IS_WORKER, csv, env, flag

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
BUILD_ONLY = os.environ.get('DJANGO_SETTINGS_MODULE') == 'myproject.settings_build'
DEBUG = flag('DEBUG', not IS_WORKER and not bool(env('RENDER')))
SECRET_KEY = env('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG or BUILD_ONLY:
        SECRET_KEY = 'django-insecure-local-development-and-static-build-only'
    else:
        raise ImproperlyConfigured('Set a unique SECRET_KEY for production.')

# SECURITY WARNING: don't run with debug turned on in production!

ALLOWED_HOSTS = csv('ALLOWED_HOSTS', '127.0.0.1,localhost')
if render_host := env('RENDER_EXTERNAL_HOSTNAME'):
    ALLOWED_HOSTS.append(render_host)

CSRF_TRUSTED_ORIGINS = csv('CSRF_TRUSTED_ORIGINS')
SESSION_COOKIE_SECURE = flag('SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = flag('CSRF_COOKIE_SECURE', not DEBUG)
if env('RENDER'):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
if IS_WORKER:
    MIDDLEWARE.remove('whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = env('DATABASE_URL').strip()
DB_BACKEND = env('DB_BACKEND', 'd1' if IS_WORKER else ('postgresql' if DATABASE_URL else 'sqlite'))
if BUILD_ONLY:
    DATABASES = {'default': {'ENGINE': 'django.db.backends.dummy'}}
elif IS_WORKER:
    if DB_BACKEND != 'd1' or DATABASE_URL:
        raise ImproperlyConfigured('Python Workers use D1 here. DATABASE_URL/Neon is supported on Render or another native Python host.')
    DATABASES = {'default': {
        'ENGINE': 'django_cf.db.backends.d1',
        'CLOUDFLARE_BINDING': 'DB',
    }}
elif DB_BACKEND == 'postgresql':
    if not DATABASE_URL:
        raise ImproperlyConfigured('DB_BACKEND=postgresql requires DATABASE_URL.')
    import dj_database_url

    DATABASES = {'default': dj_database_url.parse(
        DATABASE_URL, conn_max_age=int(env('DB_CONN_MAX_AGE', '0')),
        conn_health_checks=True,
    )}
    if DATABASES['default']['ENGINE'] != 'django.db.backends.postgresql':
        raise ImproperlyConfigured('DATABASE_URL must be a PostgreSQL connection URL.')
    # Compatible with Neon pooled connections (PgBouncer transaction mode).
    DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True
elif DB_BACKEND == 'sqlite':
    if DATABASE_URL:
        raise ImproperlyConfigured('Remove DB_BACKEND=sqlite to enable DATABASE_URL.')
    DATABASES = {'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': env('SQLITE_PATH', str(BASE_DIR / 'db.sqlite3')),
        'OPTIONS': {'timeout': 20},
    }}
else:
    raise ImproperlyConfigured('DB_BACKEND must be sqlite or postgresql on a native host, or d1 inside Workers.')


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Asia/Almaty'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = env('MEDIA_URL', '/media/')
MEDIA_ROOT = env('MEDIA_ROOT', str(BASE_DIR / 'media'))
SERVE_LOCAL_MEDIA = flag('SERVE_LOCAL_MEDIA', DEBUG)
MEDIA_MAX_FILE_SIZE = (1 if IS_WORKER else 5) * 1024 * 1024

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}

if not IS_WORKER and (not DEBUG or env('RENDER') or flag('FORCE_MANIFEST_STATIC')):
    STORAGES['staticfiles']['BACKEND'] = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

if IS_WORKER:
    STORAGES['default'] = {
        'BACKEND': 'myproject.image_storage.DatabaseImageStorage',
    }
    FILE_UPLOAD_HANDLERS = ['myproject.uploads.WorkerImageUploadHandler']
    FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024
    DATA_UPLOAD_MAX_MEMORY_SIZE = 6 * 1024 * 1024

WHITENOISE_MAX_AGE = 31536000

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
