# Generated by Django 5.2.15 on 2026-06-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='заголовок')),
                ('category', models.CharField(choices=[('Поступление', 'Поступление'), ('Партнёрства', 'Партнёрства'), ('Развитие', 'Развитие')], max_length=40, verbose_name='категория')),
                ('date', models.CharField(max_length=80, verbose_name='дата на сайте')),
                ('text', models.TextField(verbose_name='текст')),
                ('image', models.CharField(default='myapp/images/content/ak-suu-kutbilim-visit-opt.webp', help_text='Например: myapp/images/content/ak-suu-kutbilim-visit-opt.webp', max_length=220, verbose_name='изображение из static')),
                ('order', models.PositiveIntegerField(default=100, verbose_name='порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
            ],
            options={
                'verbose_name': 'новость лицея',
                'verbose_name_plural': 'новости лицея',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
