# Generated by Django 5.2.15 on 2026-06-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_replace_bw_news_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Для новых новостей удобнее загрузить фото здесь. Оно будет показываться вместо static-пути выше.', upload_to='news/', verbose_name='загрузить изображение'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='image',
            field=models.CharField(blank=True, default='myapp/images/content/ak-suu-kutbilim-visit-opt.webp', help_text='Например: myapp/images/content/ak-suu-kutbilim-visit-opt.webp. Можно оставить пустым, если загружено фото ниже.', max_length=220, verbose_name='изображение из static'),
        ),
    ]
