# Generated by Django 6.0.6 on 2026-09-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_newsitem_image_file_alter_newsitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('name', models.CharField(max_length=220, primary_key=True, serialize=False)),
                ('content_base64', models.TextField()),
                ('size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
